In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow_data_validation as tfdv

In [4]:
# Load data from local directory:
df = pd.read_csv("../data/raw_data/raw_census.csv", skipinitialspace=True)
df.head()

,age,workclass,fnlgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
# Use TFDV to look at the statistics of the dataset:
stats = tfdv.generate_statistics_from_dataframe(dataframe=df, n_jobs=-1)
tfdv.visualize_statistics(stats)

In [11]:
# Use TFDV to look at the schema of the dataset:
schema = tfdv.infer_schema(statistics=stats)
tfdv.display_schema(schema=schema)

                    Type  Presence Valency            Domain
Feature name
'age'                INT  required                         -
'workclass'       STRING  required               'workclass'
'fnlgt'              INT  required                         -
'education'       STRING  required               'education'
'education-num'      INT  required                         -
'marital-status'  STRING  required          'marital-status'
'occupation'      STRING  required              'occupation'
'relationship'    STRING  required            'relationship'
'race'            STRING  required                    'race'
'sex'             STRING  required                     'sex'
'capital-gain'       INT  required                         -
'capital-loss'       INT  required                         -
'hours-per-week'     INT  required                         -
'native-country'  STRING  required          'native-country'
'salary'          STRING  required                  'salary'

/Users/dansun/opt/anaconda3/envs/tfx/lib/python3.6/site-packages/tensorflow_data_validation/utils/display_util.py:138: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('max_colwidth', -1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Values
Domain
'workclass'       '?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private', 'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'
'education'       '10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th', 'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad', 'Masters', 'Preschool', 'Prof-school', 'Some-college'
'marital-status'  'Divorced', 'Married-AF-spouse', 'Married-civ-spouse', 'Married-spouse-absent', 'Never-married', 'Separated', 'Widowed'
'occupation'      '?', 'Adm-clerical', 'Armed-Forces', 'Craft-repair', 'Exec-managerial', 'Farming-fishing', 'Handlers-cleaners', 'Machine-op-inspct', 'Other-service', 'Priv-house-serv', 'Prof-specialty', 'Protective-serv', 'Sales', 'Tech-support', 'Transport-moving'
'relationship'    'Husband', 'Not-in-family', 'Other-relative', 'Own-child', 'Unmarried', 'Wife'
'race'            'Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other', 'White'
'sex'             'Female', 'Male'
'native-country'  '?', 'Cambodia', 'Canada', 'China', 'Columbia', 'Cuba', 'Dominican-Republic', 'Ecuador', 'El-Salvador', 'England', 'France', 'Germany', 'Greece', 'Guatemala', 'Haiti', 'Holand-Netherlands', 'Honduras', 'Hong', 'Hungary', 'India', 'Iran', 'Ireland', 'Italy', 'Jamaica', 'Japan', 'Laos', 'Mexico', 'Nicaragua', 'Outlying-US(Guam-USVI-etc)', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto-Rico', 'Scotland', 'South', 'Taiwan', 'Thailand', 'Trinadad&Tobago', 'United-States', 'Vietnam', 'Yugoslavia'
'salary'          '<=50K', '>50K'

In [13]:
# Use TFDV to check anomalies:
anomalies = tfdv.validate_statistics(statistics=stats, schema=schema)
tfdv.display_anomalies(anomalies=anomalies)

#### Data Preprocessing

In [15]:
# Drop rows containing "?" values:
pre_shape = df.shape
df.replace(to_replace="?", value=np.nan, inplace=True)
df.dropna(axis=0, inplace=True)
post_shape = df.shape

print(f"{pre_shape[0] - post_shape[0]} rows has been dropped.")

2399 rows has been dropped.

In [20]:
# Drop columns containing too many zero values:
df.drop(columns=["capital-loss", "capital-gain"], inplace=True)

# Drop column "fnlgt" which seems like an ID column
df.drop(columns=["fnlgt"], inplace=True)